
stages:
  - quality

.generic: &generic
  image: 'registry.gitlab.com/arnapou/docker/php:8.3-dev'
  stage: quality
  only:
    - master
  before_script:
    - composer install --no-interaction --optimize-autoloader --dev
  cache:
    key: "$CI_COMMIT_REF_SLUG:$CI_JOB_NAME"
    paths:
      - vendor

test:
  <<: *generic
  script:
    - vendor/bin/phpunit

cs:
  <<: *generic
  variables:
    PHP_CS_FIXER_IGNORE_ENV: 1
  script:
    - vendor/bin/php-cs-fixer fix --using-cache=no --dry-run

sa:
  <<: *generic
  script:
    - vendor/bin/phpstan
