
stages:
  - quality

PHP:
  image: "registry.gitlab.com/arnapou/docker/php:${PHPVER}-dev"
  stage: quality
  before_script:
    - composer install --no-interaction --no-progress --quiet
  script:
    - composer run cs
    - composer run sa
    - composer run test
  cache:
    key: "${PHPVER}:${CI_COMMIT_REF_SLUG}:${CI_JOB_NAME}"
    paths: [vendor]
  parallel:
    matrix:
      - PHPVER: [ '8.3', '8.4' ] # TODO '8.5'
